Copy /Y /A "GweTest.mfsim.nam" "mfsim.nam"
call "C:\Program Files\USGS\ModelMuse5\bin\ModelMonitor.exe" -m C:\WRDAPP\mf6.6.2_win64\bin\mf6.exe -n mfsim.nam -mv 6
"Mf6ObsExtractor.exe" GweTest.Mf6WriteIns
Start C:\ModelingTools\ModelMonitor\Release\Win64\ListingAnalyst.exe GweTest.lst
Start C:\ModelingTools\ModelMonitor\Release\Win64\ListingAnalyst.exe mfsim.lst
Start C:\ModelingTools\ModelMonitor\Release\Win64\ListingAnalyst.exe GweTest.Chem.lst
Start C:\ModelingTools\ModelMonitor\Release\Win64\ListingAnalyst.exe GweTest.Temperature.lst
pause
