#Script for PLPROC

#Read parameter values
K = 1
# Pilot points are used with K.

#Read pilot point data
KPilotPoints1 = read_list_file(skiplines=0,dimensions=2, &
  plist='K_1';column=5, &
  id_type='character',file='RmaVoronoiPrt.Kx.K.1.pp')

#Read MODFLOW 6 grid information file
cl_Discretization1 = read_mf6_grid_specs(file='RmaVoronoiPrt.disv.grb', &
  dimensions=2, &
  slist_layer_idomain=id1; layer=1, &
  plist_layer_bottom =bot1; layer=1, &
  plist_top = top)



# Layer     1

#Read data to modify
read_list_file(reference_clist='cl_Discretization1',skiplines=1, &
  slist=s_PIndex1;column=2, &
  plist=p_Value1;column=3, &
  file='RmaVoronoiPrt.Kx.PstValues')

# Modfify data values
temp1=new_plist(reference_clist=cl_Discretization1,value=0.0)
# Setting values for layer     1
  # Setting values for parameter K
    # Substituting interpolated values
    # Get interpolated values
    temp1=K_1.krige_using_file(file='RmaVoronoiPrt.Kx.Factors1';form='formatted', &
      transform='log')
    # Write interpolated values in zones
    p_Value1(select=(s_PIndex1 == 1)) = temp1

#Write new data values
write_column_data_file(header='no', &
  file='arrays\RmaVoronoiPrt.Kx_1.arrays';delim="space", &
  plist=p_Value1)

# Remove sLists and pLists
s_PIndex1.remove()
K_1.remove()
temp1.remove()

